### ISSUE TITLE
Error after last update

### ISSUE THREAD

**Issue by validoll** [donquixote/cellbrush#1]
I get error:

> Access level to Donquixote\Cellbrush\Table\Table::renderAttributes() must be public (as in class Donquixote\Cellbrush\Html\AttributesGetterInterface) in vendor/donquixote/cellbrush/src/Table/Table.php on line 111

**Comment by donquixote** [comment]
Awesome, someone is using this :)

**Comment by donquixote** [comment]
Two options:
1. Remove the AttributesGetterInterface from TableInterface.
2. Make the method public in Table.

**Comment by donquixote** [comment]
Too bad that PhpStorm does not detect this stuff if it happens in traits.

**Comment by ghost** [comment]
@donquixote Have this problem too, but none of your solutions worked! :\

**Comment by donquixote** [comment]
@sebascar So you are using a version with the above PR included, but you still see an error?

**Comment by ghost** [comment]
@donquixote  Thanks for your reply. **Solved** :)

I tried to install CelBrush via composer specifing 1.0.2 as version, but did not work (why?). I edited the files manually, works perfectly

By the way, thanks SO MUCH for your contribute.

**Comment by donquixote** [comment]
Do you get the fix if you use the dev version?
Then maybe I just need to make a new release.

(Sorry atm I don't have time to look at the code myself, my eyes are on another project)

**Comment by donquixote** [comment]
And out of curiosity: Can you describe the use case where you use the library?

**Comment by mcaskill** [comment]
@sebascar It's been a while since I've worked on this library but maybe try my fork: https://github.com/mcaskill/cellbrush/commits/develop which addressed a number of issues I encountered when using it for a spots results project.

**Comment by donquixote** [comment]
@mcaskill Would have been nice to ping me about your fork! But nice that others are interested in it.
(no bad feelings, just saying)

Maybe I will merge or cherry-pick some of your changes, will see.

**Comment by mcaskill** [comment]
Wanted to offer a PR but got caught up in another project followed by another one and haven't been able to revisit it since. I'll try and find some time for it.

**Comment by donquixote** [comment]
@mcaskill The PR is nice but not super important. Now that I know about it, I can simply review the individual commits and then cherry-pick what I like. I'll try to make sure that you show up as the commit author.

**Comment by ghost** [comment]
@donquixote Thanks for your question. I'm using as part of collection of tools. In particular I use CellBrush to generate a dynamic <table> from the user's input.

If you have any other question I'll be glad to help :)

@mcaskill, thanks! I'll take a look, but up to now cellbrush is doing it's dirty job :)

**Comment by danijelk** [comment]
Please do cherry-pick the fix @donquixote, we can't seem to use @mcaskill git repo in composer as he changed the .composer file so "donquixote/cellbrush" can't be overwritten using "repositories" in composer.json, and without a stable release in his repo there is nothing we can do (we cannot manually edit vendor files), thanks! 👍

**Comment by donquixote** [comment]
I'll do it today, promise :)

**Comment by mcaskill** [comment]
@danijelk I used my fork like so in a project:

``` json
"repositories": [
    {
        "type": "git",
        "url": "https://github.com/mcaskill/cellbrush.git"
    }
],
"require": {
    "mcaskill/cellbrush": "dev-develop",
},
"replace": {
    "donquixote/cellbrush": "*"
}
```

Maybe that could help in the meantime. Don't remember why I changed the vendor name. Probably related to how little I knew about using Composer at the time.

**Comment by donquixote** [comment]
Since this error seems to be identical with #3, I suppose this one is now also fixed.
New release 1.0.3.

Btw the reason I did not notice this is that my system gives me PHP 5.5.9 by default, which does not care about the access modifier.

And: Both this issue and #3 are examples of really poor issue titles :) C'mon, you can do better! There is a good chance this would have been fixed by now with a clear issue title.

**Comment by donquixote** [comment]
https://3v4l.org/tJY7u

**Comment by donquixote** [comment]
Perhaps I spoke too soon.
There are still failing tests, and issues with public / protected.

I also notice this code:

``` php
class Attributes implements AttributesInterface {

  use AttributesTrait {
    renderAttributes as public;
    renderTag as public;
  }
}
```

I think the idea was to give the trait members restricted access, but then optionally change visibility to public in the use statement.

More about this soon (today).

**Comment by donquixote** [comment]
Ok, now the build is green!
Release: 1.0.4

In the existing codebase, `MutableAttributesTrait` is always used in classes which implement `MutableAttributesInterface`. Hence, the methods can be public by default.

`AttributesTrait` is also used in classes where the methods are not meant to be public. Hence, b87b0a9279 only adds a "createTag as public" in the use statement.

**Comment by donquixote** [comment]
And now I am going to look at the stuff from @mcaskill

**Comment by donquixote** [comment]
Btw sorry I missed to give commit credit for the two fixes, which I imagine were somewhere in @mcaskill's repo. I quickly made the fixes myself instead.

**Comment by donquixote** [comment]
@mcaskill I also added a .gitignore based on commits in your fork.
See https://github.com/donquixote/cellbrush/commits/09c70b421828624756e56591de41d5e86030f50e

**Comment by donquixote** [comment]
@mcaskill For further changes from your repo, we should open dedicated issues.
I had a look at your repo, but then gave up.. I cannot decide that easily what I want to pick and what I don't. Better to have issues to discuss the changes.
(If you have the time and patience for this)

**Comment by mcaskill** [comment]
That would be a good idea. I need to take some time to reacquaint myself with the codebase and the various changes and fixes I made over time.

**Comment by donquixote** [comment]
And I am careful with commits because all I commit then needs to be BC-supported. I cannot add a feature and then remove it later.

I also have some local changes which attempt to make things more "solid"..
