### ISSUE TITLE
Got an error when trying to use test file

### ISSUE THREAD

**Issue by gagantous** [donquixote/cellbrush#10]
how do i use this function in  php ?
i got an error just like this
`Fatal error: Class 'PHPUnit_Framework_TestCase' not found in C:\xampp\htdocs\cellbrush\tests\src\CellbrushTest.php on line 7`

thanks in advance

**Comment by donquixote** [comment]
You run the test classes with PhpUnit.
Otherwise you don't touch them.

If you don't know what PhpUnit is, the best you can do is just ignore these folders.
Or you learn about PhpUnit, which is a good idea for every PHP developer.
