### ISSUE TITLE
How can i use it with Laravel(Installation)

### ISSUE THREAD

**Issue by dalwinder23** [donquixote/cellbrush#12]
I have tried with Laravel 5.4(Installation). Error: "Class 'Donquixote\Cellbrush\Table\Table' not found"

**Comment by vkrtecek** [comment]
Did you try to make new autoload file (composer dump-autoload) after instalation?

**Comment by donquixote** [comment]
Yeah, I don't see why this would not work.
Composer require, then you should be good to go.

Reopen, or create a more specific bug report, if you continue having issues.
