### ISSUE TITLE
No feature for adding `id` attribute to a table yet. How?

### ISSUE THREAD

**Issue by makoru-hikage** [donquixote/cellbrush#4]
Such as `<table id="table1">...</table>`

Am I mistaken?

The `id` attribute is always important.

**Comment by makoru-hikage** [comment]
I figured out how to create such attribute, but the `createTag()` method of `MutableAttributesTrait` as `use`d by `Table` class creates an error: `Cannot access private property Donquixote\Cellbrush\Html\Tag::$attributes` 

All I did was just this:

```
$table = \Donquixote\Cellbrush\Table\Table::create()
      ->addRowNames(['row0', 'row1', 'row2'])
      ->addColNames(['col0', 'col1', 'col2'])
      ->td('row0', 'col0', 'Diag 0')
      ->td('row1', 'col1', 'Diag 1')
      ->td('row2', 'col2', 'Diag 2')
    ;

    $table->createTag('id');

    $html = $table->render();
```

This line `$table->createTag('id');` bears the problem.

**Comment by donquixote** [comment]
Oh btw I don't think that Table should have a ->createTag() method. Certainly not with the purpose of setting the id.

And btw I have a new branch of this library somewhere, with a lot of changes, but I cannot find the time to bring it over the finish line :(

**Comment by donquixote** [comment]
Do you think 'id' will be needed a lot? And do you think we should support arbitrary attributes on every element of the table?

**Comment by makoru-hikage** [comment]
For `$table->createTag('id');` my horrible mistake. I was too ignorant. My bad. 

I got a solution. Why is that `MutableAttributesTrait` has no method to set `$attributes` aside from modifying classes (`addClass()` and `addClasses()`)? "Mutable" means "can be changed". So I made a PR. About your question with the `id` attribute, note that some web pages can have many tables within.

Also, `id` attribute is crucial for using the jQuery [DataTables](https://datatables.net/). Attributes are versatile.

Thank you for your response.

**Comment by donquixote** [comment]
> Why is that MutableAttributesTrait has no method to set $attributes aside from modifying classes (addClass() and addClasses())?

Because I was lazy :)

**Comment by makoru-hikage** [comment]
> Because I was lazy :)

HEHEHEHEHEHEHEHEHEHEHE

**Comment by chamuridis** [comment]
Hello!

Very useful instrumen!

Please add a method to add "id", its very important!

**Comment by donquixote** [comment]
Fixed. See:
- #8 
- #23
